# Site settings
title: "Big Book of Brews"
author: "Saph, Traneptora"
description:
  "A searchable D&D 5e spell list, sorted by class and level."
baseurl: "Big-Book-of-Brews" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
