title: Big Book of Brews
email: GrimoireCebuli@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This website is a collection of homebrew spells.
  The collection includes original homebrew material,
  along with edited or copied spells from
  numerous published homebrew sources.

  These sources include
  Kobold Press's Deep Magic series,
  Grim Hollow Player's Guide,
  and the Necromancer Games's Book of Lost Spells.
  Each spell present on the website i
  credited to its source.
baseurl: "Big-Book-of-Brews" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
